import type {
  AuditLogEntry,
  Booking,
  BookingSlot,
  Client,
  Communication,
  Invitation,
  LoanApplication,
  Service,
  StaffAccount,
  UploadedDoc,
} from "./types";

export const lenders = ["ANZ", "CommBank", "NAB", "Westpac", "St. George", "ING"];

export const clients: Client[] = [
  { id: "cl-001", name: "Maria Dela Cruz", email: "maria.delacruz@email.com", phone: "+61 400 111 234" },
  { id: "cl-002", name: "Marco Reyes", email: "marco.reyes@email.com", phone: "+61 400 222 345" },
  { id: "cl-003", name: "Ailey Santos", email: "ailey.santos@email.com", phone: "+61 400 333 456" },
  { id: "cl-004", name: "Dara Lim", email: "dara.lim@email.com", phone: "+61 400 444 567" },
  { id: "cl-005", name: "Kelvin Ocampo", email: "kelvin.ocampo@email.com", phone: "+61 400 555 678" },
  { id: "cl-006", name: "Suri Lozano", email: "suri.lozano@email.com", phone: "+61 400 666 789" },
];

export const applications: LoanApplication[] = [
  {
    id: "APP-2041",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "ANZ",
    amount: 480000,
    purpose: "Home refinance",
    termMonths: 360,
    status: "In Review",
    updatedAt: "12 Aug 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2038",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "CommBank",
    amount: 350000,
    purpose: "Investment property",
    termMonths: 300,
    status: "Additional Info Requested",
    updatedAt: "09 Aug 2026",
    broker: "Jamie Ramirez",
    actionNeeded: "Please upload your latest payslip",
  },
  {
    id: "APP-2035",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "NAB",
    amount: 120000,
    purpose: "Debt consolidation",
    termMonths: 120,
    status: "Approved",
    updatedAt: "01 Aug 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2029",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "Westpac",
    amount: 45000,
    purpose: "Car purchase",
    termMonths: 60,
    status: "Submitted",
    updatedAt: "28 Jul 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2018",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "ANZ",
    amount: 30000,
    purpose: "Personal loan",
    termMonths: 48,
    status: "Declined",
    updatedAt: "14 Jul 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2004",
    clientId: "cl-001",
    clientName: "Maria Dela Cruz",
    lender: "St. George",
    amount: 520000,
    purpose: "Home purchase",
    termMonths: 360,
    status: "Settled",
    updatedAt: "20 Jun 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2042",
    clientId: "cl-002",
    clientName: "Marco Reyes",
    lender: "CommBank",
    amount: 690000,
    purpose: "Home purchase",
    termMonths: 360,
    status: "Submitted",
    updatedAt: "15 Aug 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2040",
    clientId: "cl-003",
    clientName: "Ailey Santos",
    lender: "ANZ",
    amount: 210000,
    purpose: "Home refinance",
    termMonths: 240,
    status: "In Review",
    updatedAt: "11 Aug 2026",
    broker: "Bianca Torres",
  },
  {
    id: "APP-2039",
    clientId: "cl-004",
    clientName: "Dara Lim",
    lender: "Westpac",
    amount: 180000,
    purpose: "Investment property",
    termMonths: 300,
    status: "Additional Info Requested",
    updatedAt: "10 Aug 2026",
    broker: "Bianca Torres",
  },
  {
    id: "APP-2036",
    clientId: "cl-005",
    clientName: "Kelvin Ocampo",
    lender: "NAB",
    amount: 95000,
    purpose: "Debt consolidation",
    termMonths: 120,
    status: "Approved",
    updatedAt: "02 Aug 2026",
    broker: "Jamie Ramirez",
  },
  {
    id: "APP-2031",
    clientId: "cl-006",
    clientName: "Suri Lozano",
    lender: "St. George",
    amount: 560000,
    purpose: "Home purchase",
    termMonths: 360,
    status: "In Review",
    updatedAt: "30 Jul 2026",
    broker: "Bianca Torres",
  },
];

export const communications: Communication[] = [
  {
    id: "cm-1",
    subject: "Payslip requested for APP-2038",
    from: "Jamie Ramirez (BAI Finance)",
    to: "maria.delacruz@email.com",
    timestamp: "15 Aug 2026, 9:42 AM",
    direction: "outbound",
    read: true,
    preview:
      "Hi Maria, to keep your CommBank application moving we'll need your latest payslip…",
  },
  {
    id: "cm-2",
    subject: "Re: Payslip requested for APP-2038",
    from: "Maria Dela Cruz",
    to: "Jamie Ramirez (BAI Finance)",
    timestamp: "15 Aug 2026, 11:05 AM",
    direction: "inbound",
    read: true,
    preview:
      "Thanks Jamie — I'll upload it through the portal today, the payslip for July is ready…",
  },
  {
    id: "cm-3",
    subject: "ANZ home refinance — valuation booked",
    from: "Jamie Ramirez (BAI Finance)",
    to: "maria.delacruz@email.com",
    timestamp: "11 Aug 2026, 2:18 PM",
    direction: "outbound",
    read: true,
    preview:
      "Good news! The bank has scheduled the property valuation for this Thursday…",
  },
  {
    id: "cm-4",
    subject: "NAB approval — next steps",
    from: "Jamie Ramirez (BAI Finance)",
    to: "maria.delacruz@email.com",
    timestamp: "01 Aug 2026, 4:30 PM",
    direction: "outbound",
    read: true,
    preview:
      "Congratulations Maria, your debt consolidation loan of $120,000 has been approved…",
  },
  {
    id: "cm-5",
    subject: "Welcome to BAI Finance",
    from: "BAI Finance Client Care",
    to: "maria.delacruz@email.com",
    timestamp: "24 Jun 2026, 10:00 AM",
    direction: "outbound",
    read: true,
    preview:
      "Welcome! This portal gives you a single view of your loan applications and documents…",
  },
];

export const uploadedDocs: UploadedDoc[] = [
  { id: "dc-1", name: "payslip-june-2026.pdf", type: "PDF", size: "248 KB", status: "Reviewed" },
  { id: "dc-2", name: "payslip-may-2026.pdf", type: "PDF", size: "251 KB", status: "Reviewed" },
  { id: "dc-3", name: "tax-return-2025.pdf", type: "PDF", size: "1.2 MB", status: "In Review" },
  { id: "dc-4", name: "id-passport.jpg", type: "JPG", size: "610 KB", status: "Uploaded" },
  { id: "dc-5", name: "bank-statements-q2.pdf", type: "PDF", size: "820 KB", status: "Reviewed" },
];

export const bookings: Booking[] = [
  { id: "bk-1", clientName: "Maria Dela Cruz", topic: "ANZ refinance review", dateTime: "Thu 20 Aug, 10:00 AM", status: "Confirmed" },
  { id: "bk-2", clientName: "Marco Reyes", topic: "New home purchase — intro", dateTime: "Fri 21 Aug, 2:30 PM", status: "Confirmed" },
  { id: "bk-3", clientName: "Ailey Santos", topic: "Valuation follow-up", dateTime: "Mon 24 Aug, 11:00 AM", status: "Pending" },
  { id: "bk-4", clientName: "Suri Lozano", topic: "St. George pre-approval", dateTime: "18 Aug 2026, 9:00 AM", status: "Completed" },
];

export const invitations: Invitation[] = [
  {
    id: "inv-1",
    name: "Liah Fernandez",
    email: "liah.fernandez@email.com",
    phone: "+61 400 777 890",
    inviteStatus: "Sent",
    verificationStatus: "Pending",
    sentAt: "18 Aug 2026",
    notes: "Referred by Brent Tan",
  },
  {
    id: "inv-2",
    name: "Owen Villanueva",
    email: "owen.villanueva@email.com",
    phone: "+61 400 888 901",
    inviteStatus: "Sent",
    verificationStatus: "Pending",
    sentAt: "18 Aug 2026",
  },
  {
    id: "inv-3",
    name: "Mika Reyes",
    email: "mika.reyes@email.com",
    phone: "+61 400 999 012",
    inviteStatus: "Activated",
    verificationStatus: "Verified",
    sentAt: "12 Aug 2026",
    notes: "ID verified via passport",
  },
  {
    id: "inv-4",
    name: "Jude Santos",
    email: "jude.santos@email.com",
    phone: "+61 400 111 345",
    inviteStatus: "Activated",
    verificationStatus: "Flagged",
    sentAt: "09 Aug 2026",
    notes: "Address mismatch on ID — review",
  },
  {
    id: "inv-5",
    name: "Nadia Cruz",
    email: "nadia.cruz@email.com",
    phone: "+61 400 222 456",
    inviteStatus: "Expired",
    verificationStatus: "Pending",
    sentAt: "28 Jul 2026",
    notes: "Invite link lapsed after 30 days",
  },
  {
    id: "inv-6",
    name: "Felix Bautista",
    email: "felix.bautista@email.com",
    phone: "+61 400 333 567",
    inviteStatus: "Activated",
    verificationStatus: "Verified",
    sentAt: "25 Jul 2026",
  },
];

export const auditLog: AuditLogEntry[] = [
  { id: "al-1", timestamp: "2026-08-18 11:26:34", actor: "broker.jramirez@bai.com", action: "VIEW_DOCUMENT", entityType: "Application", entityId: "APP-2038", ip: "203.0.113.24" },
  { id: "al-2", timestamp: "2026-08-18 11:20:11", actor: "client.mdelacruz@email.com", action: "UPLOAD_DOCUMENT", entityType: "Document", entityId: "DC-2038-PL", ip: "198.51.100.77" },
  { id: "al-3", timestamp: "2026-08-18 10:58:03", actor: "compliance.kchen@bai.com", action: "REQUEST_INFO", entityType: "Application", entityId: "APP-2039", ip: "203.0.113.88" },
  { id: "al-4", timestamp: "2026-08-18 09:41:52", actor: "broker.btorres@bai.com", action: "SEND_EMAIL", entityType: "Communication", entityId: "CM-2041-02", ip: "203.0.113.41" },
  { id: "al-5", timestamp: "2026-08-17 16:12:09", actor: "compliance.kchen@bai.com", action: "SEND_INVITE", entityType: "Invitation", entityId: "INV-1046", ip: "203.0.113.88" },
  { id: "al-6", timestamp: "2026-08-17 15:33:27", actor: "broker.jramirez@bai.com", action: "CREATE_APPLICATION", entityType: "Application", entityId: "APP-2042", ip: "203.0.113.24" },
  { id: "al-7", timestamp: "2026-08-17 14:05:44", actor: "client.mreyes@email.com", action: "VIEW_APPLICATION", entityType: "Application", entityId: "APP-2042", ip: "198.51.100.90" },
  { id: "al-8", timestamp: "2026-08-17 11:47:18", actor: "admin.sgarcia@bai.com", action: "APPROVE_APPLICATION", entityType: "Application", entityId: "APP-2036", ip: "203.0.113.10" },
  { id: "al-9", timestamp: "2026-08-17 09:02:55", actor: "compliance.kchen@bai.com", action: "FLAG_ACCOUNT", entityType: "Client", entityId: "cl-1044", ip: "203.0.113.88" },
  { id: "al-10", timestamp: "2026-08-16 17:58:31", actor: "broker.btorres@bai.com", action: "REVOKE_INVITE", entityType: "Invitation", entityId: "INV-1031", ip: "203.0.113.41" },
  { id: "al-11", timestamp: "2026-08-16 13:22:47", actor: "client.slozano@email.com", action: "LOGIN", entityType: "Session", entityId: "SES-22041", ip: "198.51.100.112" },
  { id: "al-12", timestamp: "2026-08-16 10:39:14", actor: "broker.jramirez@bai.com", action: "UPDATE_APPLICATION", entityType: "Application", entityId: "APP-2040", ip: "203.0.113.24" },
];

export const services: Service[] = [
  {
    id: "home-loans",
    name: "Home Loans",
    blurb: "First home, upgrade or investment — we compare lenders and manage the whole application for you.",
    features: ["Owner-occupier & investor rates", "Fixed, variable & split options", "Refinancing to lower your rate", "Pre-approval guidance"],
    icon: "Home",
  },
  {
    id: "personal-loans",
    name: "Personal Loans",
    blurb: "Unsecured lending for a purchase, holiday or consolidation — tailored to your situation.",
    features: ["Fixed repayments from $5k", "Fast turnaround", "No hidden fees", "Debt consolidation options"],
    icon: "Wallet",
  },
  {
    id: "refinance",
    name: "Refinancing",
    blurb: "We review your current home loan and move you to a better rate when it makes sense.",
    features: ["Rate comparison across lenders", "Cash-out for renovations", "Fee & cost modelling", "Settlement handled end-to-end"],
    icon: "Refresh",
  },
  {
    id: "investment",
    name: "Investment Lending",
    blurb: "Grow your portfolio with investment property finance structured around your strategy.",
    features: ["Interest-only periods", "Cross-collateralisation advice", "Commercial & residential", "SMSF-friendly lenders"],
    icon: "TrendingUp",
  },
  {
    id: "construction",
    name: "Construction & Building",
    blurb: "Progress-payment construction loans to get your build started and keep it moving.",
    features: ["Progress draws scheduled", "Land + build packages", "Builder payment management", "Project timelines tracked"],
    icon: "Building",
  },
  {
    id: "car-asset",
    name: "Car & Asset Finance",
    blurb: "Competitive rates on vehicles and business assets with flexible terms.",
    features: ["New & used vehicles", "Chattel & lease structures", "Deposit & balloon options", "GST handling for business"],
    icon: "Car",
  },
];

export const bookingSlots: BookingSlot[] = [
  { id: "sl-01", broker: "Jamie Ramirez", date: "Thu 20 Aug", time: "9:00 AM", status: "available" },
  { id: "sl-02", broker: "Jamie Ramirez", date: "Thu 20 Aug", time: "10:00 AM", status: "available" },
  { id: "sl-03", broker: "Jamie Ramirez", date: "Thu 20 Aug", time: "11:00 AM", status: "booked" },
  { id: "sl-04", broker: "Jamie Ramirez", date: "Thu 20 Aug", time: "2:00 PM", status: "available" },
  { id: "sl-05", broker: "Jamie Ramirez", date: "Fri 21 Aug", time: "9:30 AM", status: "available" },
  { id: "sl-06", broker: "Jamie Ramirez", date: "Fri 21 Aug", time: "11:00 AM", status: "booked" },
  { id: "sl-07", broker: "Jamie Ramirez", date: "Fri 21 Aug", time: "1:30 PM", status: "available" },
  { id: "sl-08", broker: "Jamie Ramirez", date: "Fri 21 Aug", time: "3:00 PM", status: "available" },
  { id: "sl-09", broker: "Jamie Ramirez", date: "Mon 24 Aug", time: "10:00 AM", status: "available" },
  { id: "sl-10", broker: "Jamie Ramirez", date: "Mon 24 Aug", time: "2:00 PM", status: "available" },
  { id: "sl-11", broker: "Jamie Ramirez", date: "Tue 25 Aug", time: "9:00 AM", status: "booked" },
  { id: "sl-12", broker: "Jamie Ramirez", date: "Tue 25 Aug", time: "11:30 AM", status: "available" },
];

export const staffAccounts: StaffAccount[] = [
  { id: "st-01", name: "Jamie Ramirez", email: "broker.jramirez@bai.com", role: "Senior Broker", status: "Active", requestedAt: "02 Mar 2026", approvedBy: "Keanu Chen", mfa: true },
  { id: "st-02", name: "Bianca Torres", email: "broker.btorres@bai.com", role: "Broker", status: "Active", requestedAt: "18 Apr 2026", approvedBy: "Keanu Chen", mfa: true },
  { id: "st-03", name: "Keanu Chen", email: "compliance.kchen@bai.com", role: "Compliance Team", status: "Active", requestedAt: "11 Jan 2026", approvedBy: "Sofia Garcia", mfa: true },
  { id: "st-04", name: "Sofia Garcia", email: "admin.sgarcia@bai.com", role: "Compliance Team", status: "Active", requestedAt: "02 Jan 2026", approvedBy: "System", mfa: true },
  { id: "st-05", name: "Rafael Aquino", email: "broker.raquino@bai.com", role: "Broker", status: "Pending", requestedAt: "15 Aug 2026", mfa: false },
  { id: "st-06", name: "Elena Marquez", email: "broker.emarquez@bai.com", role: "Senior Broker", status: "Pending", requestedAt: "17 Aug 2026", mfa: false },
  { id: "st-07", name: "Dexter Lim", email: "broker.dlim@bai.com", role: "Broker", status: "Suspended", requestedAt: "10 Jun 2026", approvedBy: "Sofia Garcia", mfa: true },
];